### ISSUE TITLE
Stylet use Guard Properties instead of Method, so what can I  do if I want to pass an argument to it?

### ISSUE THREAD

**Issue by roycai1234** [canton7/Stylet#117]
In 'traditional' WPF, I can pass  CommandParameter to CanDoSomething() method. But how can i do with Stylet ?

for eg.
```cs
 public bool CanExecute(object parameter)
        {
            return (int)parameter >0;
        }
```

**Comment by canton7** [comment]
There's nothing built into guard properties, or indeed actions, for this: you'll have to use your own `ICommand` implementation for this, rather than using actions.

I'm happy to take a PR which looks for a guard method if it can't find a guard property. [This](https://github.com/canton7/Stylet/blob/2b80db4db7d215f76855eafa3806c450fe532de5/Stylet/Xaml/CommandAction.cs#L119) is your starting point.

**Comment by roycai1234** [comment]
Thank you very much!  I can use property IsEnabled="{Binding item, Converter={StaticResource myConverter}}" as an alternative solution for this case.
Anyway, Stylet is an excellent framework.
