### ISSUE TITLE
Conductor<T>.Collection.OneActive closes and disposes the active item twice

### ISSUE THREAD

**Issue by azabluda** [canton7/Stylet#14]
I slightly extend `Stylet.Samples.TabNavigation.Page2ViewModel` class and set the breakpoints in `OnClose` and `Dispose` methods
```cs
    class Page2ViewModel : Screen, IDisposable
    {
        public Page2ViewModel()
        {
            this.DisplayName = "Page 2";
        }

        protected override void OnClose()
        {
            base.OnClose();
        }

        public void Dispose()
        {
        }
    }
```
Now if I run the sample application, switch to the second tabsheet, and close the app, then each of my breakpoints is hit twice.

Interesting enough it doesn't seem to happen in `StyletUnitTests.ConductorOneActiveTests.ClosingClosesAllItems` unit test.

**Comment by canton7** [comment]
Interesting - `Screen` itself should prevent `OnClose()` from being called twice in a row. The conductor can, and will, call Activate/Deactivate/Close in entirely nonsensical orders, and Screen is the one that sorts that all out.

I'll try and reproduce over lunch.

**Comment by canton7** [comment]
Aright, what happens is that the parent conductor is closed, which causes it to propagate that closed event to its ActiveItem. Then it clears its list of Items, which deactivates the screen again (causing it to transition from Closed to Deactivated), then closes it again.

There are two issues here: one is that the work that the Conductor is doing is unnecessary, so that should be fixed. The other is that Closed -> Deactivated is not a valid Screen transition, so that should be fixed (and go via Activated).

**Comment by canton7** [comment]
(reopened until I release)

**Comment by azabluda** [comment]
Very impressive reaction time! Thank you @canton7 :+1:
