### ISSUE TITLE
ViewModel <-> View mapping feature

### ISSUE THREAD

**Issue by SuperBrain** [canton7/Stylet#145]
I would like to be able to tell Stylet which View should be created for which ViewModel.

I have a specific use-case where I would like to create multiple VMs but have them all use a single View. 

I understand this could be done by subclassing the ViewManager. However, having a simple dictionary that can tell Stylet to create `MyView` for both `MyViewModel` and `MyOtherViewModel` would be a nice feature.

EDIT: Someone pointed [this](https://github.com/canton7/Stylet/blob/master/Samples/Stylet.Samples.OverridingViewManager/CustomViewManager.cs) from samples, which seems to be what I need, but I don't know how I would use that?

EDIT 2: I see the Attribute in there but there's a couple of issues with it
1. You have to apply it to a View (rather than a ViewModel)
2. `AllowMultiple = false` suggests that only 1 ViewModel can be mapped to a single View

Wouldn't it be better if this attribute was applied to VMs, specifying the View that goes with them?

**Comment by canton7** [comment]
Have you read [this page from the documentation](https://github.com/canton7/Stylet/wiki/The-ViewManager)?

**Comment by SuperBrain** [comment]
Thanks for pointing that out, but I'm well aware of it (hence mentioning the sample). My question here is, would it be possible to provide one of the following solutions:
1. An easy, publicly accessible ViewModel <-> View mapper that supports 1:n mapping
2. An Attribute introduced in mentioned sample that is applied to VMs, pointing to View that needs to be created

`1.` would mean adding a new feature while `2.` would be providing another sample. Either way, this would add more value to already great library.

**Comment by canton7** [comment]
You can write whatever mapper you need.

**Comment by vgist1** [comment]
Would be really nice if Stylet had such feature without having to create your own ViewManager. I've faced a similar situation and ended up making multiple views due to the complexity of the viewmanager, to just add a few mappings. I would definitively use a feature like this if available, could be as simple as a dictionary that Stylet lookup before mapping things by itself.

**Comment by canton7** [comment]
> due to the complexity of the viewmanager

The ViewManager is simple: for your case, you can override [`LocateViewForModel`](https://github.com/canton7/Stylet/blob/a40a27fd146a4680e9eafddd262a2e3fbf7fedbe/Stylet/ViewManager.cs#L274) or [`ViewTypeNameForModelTypeName`](https://github.com/canton7/Stylet/blob/a40a27fd146a4680e9eafddd262a2e3fbf7fedbe/Stylet/ViewManager.cs#L249).

Stylet makes it easy to replace bits of the framework precisely so that you can do what you're asking, and so that I don't need to ship an infinitely-customisable ViewManager.

Stylet uses a convention-based approach, where the name of the view type is derived from the name of the ViewModel type. That, unfortunately, means you can't easily have multiple ViewModel types for a single view type: in order to do this, you need to introduce some other mechanism. There are many such mechanisms you could choose: you could use an attribute (and I've written a ViewManager which does this, see the samples), or you could add some extra conventions onto the name (SomeViewModel1 -> SomeView, etc), or some manual mapping, or... I don't think there's a best approach here, but it really is very easy to do something yourself.

Here's an example which maps `ViewModel1` to `View`:

```cs
public class MyViewManager : ViewManager
{
    protected override string ViewTypeNameForModelTypeName(string modelTypeName)
    {
        return base.ViewTypeNameForModelTypeName(Regex.Replace(modelTypeName, @"\d+$", ""));
    }
}
```

**Comment by vgist1** [comment]
@canton7 excuse my ignorance are you saying I could technically do something like this:
```cs
public class MyViewManager : ViewManager
{
    public Dictionary<string, string> Map { get; set; }
    
    protected override string ViewTypeNameForModelTypeName(string modelTypeName)
    {
        if (Map.ContainsKey(modelTypeName))
        {
            return base.ViewTypeNameForModelTypeName(Map[modelTypeName]);
        }
        return base.ViewTypeNameForModelTypeName(modelTypeName);
    }
}
```

Where map would be say
```cs
Map = new Dictionary<string, string>
{
    { "CustomerReportViewModel", "ReportViewModel" },
    { "CompanyReportViewModel", "ReportViewModel" },
    { "AccountReportViewModel", "ReportViewModel" },
};
```

**Comment by canton7** [comment]
Yes, you could do exactly that.

`NamespaceTransformations` are only for transforming namespaces -- they map e.g. `SomeLibrary.SomeViewModel` to `SomeApplication.SomeView`. This can be needed for the convention-based mapping that Stylet does out of the box.

**Comment by canton7** [comment]
Closing as no response
