### ISSUE TITLE
BindableCollection.AddRange calls CollectionChanged with e.NewItems == null

### ISSUE THREAD

**Issue by uyaem** [canton7/Stylet#154]
When calling `BindableCollection.AddRange`, the `CollectionChanged` event gets raised as expected, but the event handler's `NotifyCollectionChangedEventArgs.NewItems` is always `null`.

Expected behaviour:
The added/removed items should be listed in `e.NewItems`/`e.OldItems`, like when calling `BindableCollection.Add(...)`.

Affected version:
Stylet 1.3.4

**Comment by canton7** [comment]
The problem is [right here](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Data/BindingListCollectionView.cs,2463): `ListCollectionView` doesn't allow Add events with ranges of added items. The options are therefore 1) raise multiple Add events, or 2) raise a Reset event. We do the latter: if the user wants multiple Add events, they can call `BindableCollection.Add` multiple times themselves.

**Comment by uyaem** [comment]
Ah, I was wondering why you didn't simply use the `NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction, IList, IList)` constructor. 😃 
The implementation in `ListCollectionView` seems silly/dated...

My `BindableCollection` is initialized with multiple entries. my View contains both a `DataGrid` for editing, as well as a "graph" which should reflect any data changes on the fly, therefore I need to attach `PropertyChanged` listeners to all entries.
Seems like my "workaround" of using a loop with the `BindableCollection.Add` in the initialization must therefore become a permanent thing. 

Thanks for the clarification. 👍
