### ISSUE TITLE
Activate item with params

### ISSUE THREAD

**Issue by boop5** [canton7/Stylet#159]
It looks like that `IConductor<T>` does not provide a way to activate items with some kind of parameters. 

I want to have some kind of NavigationService which works like this

```
public void NavigateTo(Type t, IDictionary<string, object> @params) 
{
    var vm = _container.Get(t);
    var msg = new OpenPageEvent(vm, @params);
    _eventAggregator.Publish(msg);
}
```

and my conductor would do something like this

```
public void Handle(OpenPageEvent msg, IDictionary<string, object> @params) 
{
    ActivateItem(msg, @params)
}
```

----

Obviously I could create ViewModels manually and pass my parameters like that. But I'd like to do it as I explained above. Is there a way I can do that with Stylet?

**Comment by canton7** [comment]
I don't follow I'm afraid. What would ActivateItem do with the params? It also looks like you're tryingti activate the event, rather than the ViewModel?

When I do things like this, I have a navigation service, which defined a bunch of different methods which each take a set of strongly-typed parameters as necessary. So you'd call `NavigateToLogin(param1, param2)` rather than `NavigateTo(typeof(Login ViewModel), new Dictionary<string, object>() { { "param1", param1}, { "param2", param2}})`. The navigation service would then instantiate the VM and pass in the parameters as constructor parameters. This had the advantage of kit relying on weakly-typed dictionaries which only catch errors at runtime, and also means the caller doesn't need to know the type of the final ViewModel.

**Comment by boop5** [comment]
Thanks for your input. You helped me a lot.
