### ISSUE TITLE
Rationality behind the Pages folder

### ISSUE THREAD

**Issue by ShuhuaGao** [canton7/Stylet#172]
In a typical MVVM project, we set up three folders: _Models_, _ViewModels,_ and _Views_.  However, the Stylet template generates a project with a "Pages" folder, which contains both the ShellView.xaml and the ShellViewModel.cs. Is there any special purpose for this structure?

In my opinion, the template is supposed to set up two folders in consistency with other codes: _ViewModels_ containing the ShellViewModel.cs, and _Views_ for the ShellView.xaml.

**Comment by canton7** [comment]
You can do whatever you want: Stylet supports have views and viewmodels in separate folders.

The samples and tutorial use a Pages folder, because that is my personal preference and I wrote them. The template follows suit for consistency. You're free to change anything in a project generated from a template.
