### ISSUE TITLE
s:View.ActionTarget not working

### ISSUE THREAD

**Issue by Dissolution** [canton7/Stylet#20]
I'm using the View.ActionTarget redirection in my code, but it doesn't seem to be working.
This is my button:
`<Button Content="_Add" 
     s:View.ActionTarget="{Binding NestedViewModel}"
     Command="{s:Action AddItem}"/>`
However, when I click on the button, it says it cannot find the method 'AddItem' on the base ViewModel, not the one that I have indicated in ActionTarget (NestedViewModel).
I set breaks in Stylet.Xaml.View on GetActionTarget() and SetActionTarget(), neither ever appear to be called.

Is there any way for me to debug why it doesn't appear to be setting a different viewmodel to call the action upon?

**Comment by canton7** [comment]
Note that WPF doesn't call the getters/setters on dependency properties or attached properties - it accesses the backing store directly.

My best guess is that the binding's failing for some reason. Check the output window for any binding failure messages.

Otherwise, if you can come up with a small sample which reproduces the issue, I can take a look.

**Comment by canton7** [comment]
Any response? Have you managed to resolve this?

**Comment by Dissolution** [comment]
I'm sorry, yes, I was able to fix this. It was my mistake, I had the wrong sub-view set above the button and it wasn't able to find the proper nested ViewModel.

**Comment by canton7** [comment]
Cool, thanks for getting back.
