### ISSUE TITLE
Add assembly to IoC container after builder.buildContainer is called

### ISSUE THREAD

**Issue by KiceSanders** [canton7/Stylet#39]
My use case:
During my bootstrapper configure code, I don't know for sure which assemblies my views are going to be in because they are plugins that are loaded dynamically. Is there any way the IoC container can create these objects?

**Comment by canton7** [comment]
So there's a couple of parts to this answer.

Firstly, no, the ioc container is immutable once it's been built. This is because changing the configuration of the container might change how it decides to construct objects (it might choose a different constructor if different bindings are available, for example). 

However, the view-location logic relies on more than just the ioc container. It's configured by [this object](https://github.com/canton7/Stylet/blob/3b64396f5fa5c90b4a59262585416a723435a949/Stylet/Bootstrapper.cs#L51) -- the `ViewAssemblies` tells it which assemblies to search through to try and find a view with the right name, and `ViewFactory` gives it a means of constructing those types (which is set to the ioc container by default, but doesn't have to be).

If your views and ViewModels are in the same assembly, you don't have to worry about ViewAssemblies -- the ViewManager will always look for the view in the assembly which contains the ViewModel. If not, tell, ViewAssemblies can be changed after the ViewManager is constructed.

For the ViewFactory, the easiest thing to do is probably bypass the ioc container and use `Activator.CreateInstance` (assuming that all of your views have parameterless constructors. You can do this either by using your own `ViewManagerConfig`, or grabbing and changing the `ViewManager`.

```csharp
public override void ConfigureIoC(StyletIoCBuilder builder)
{
    // Replace the ViewManagerConfig with our own
    var viewManagerConfig = new ViewManagerConfig()
    {
        ViewFactory = Activator.CreateInstance,
        ViewAssemblies = new List<Assembly>() { this.GetType().Assembly }
    };
    builder.Bind<ViewManagerConfig>().ToInstance(viewManagerConfig);
}
```

... or ...
```csharp
public override void Configure()
{
    this.container.Get<ViewManager>().ViewFactory = Activator.CreateInstance;
}
```

**Comment by KiceSanders** [comment]
Thank you. The first solution was exactly what I needed!

**Comment by canton7** [comment]
Closing as resolved.
