### ISSUE TITLE
s:Action do not work correct

### ISSUE THREAD

**Issue by Xheng1213** [canton7/Stylet#74]
MainView.xaml, two button to display different usercontrol in MainWindow, it can works.
```xaml
<Window.Resources>
    <DataTemplate DataType="{x:Type local:UserControl1ViewModel}">
        <local:UserControl1View />
    </DataTemplate>
    <DataTemplate DataType="{x:Type local:UserControl2ViewModel}">
        <local:UserControl2View />
    </DataTemplate>
</Window.Resources>

<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal">
            <Button Command="{s:Action SwitchVM}" CommandParameter="uc1">UserControl1</Button>
            <Button Command="{s:Action SwitchVM}" CommandParameter="uc2">UserControl2</Button>
        </StackPanel>
        <ContentControl Grid.Row="1" Content="{Binding CurrentViewModel}" />
</Grid>
```
MainViewModel.cs
```c#
public UserControl1ViewModel UserControl1VM;
public UserControl2ViewModel UserControl2VM;
public object CurrentViewModel { get; set; }

public MainViewModel()
{
    UserControl1VM= new UserControl1ViewModel ();
    UserControl2VM= new UserControl2ViewModel ();
}

public void SwitchVM(string name)
{
    switch (name)
    {
        case "uc1":
            CurrentViewModel = UserControl1VM;
            break;
        case "uc2":
            CurrentViewModel = UserControl2VM;
            break;
    }
} 
```
**But in usercontrol, it does not works correctly.**
UserControl1View.xaml
```xaml
<StackPanel>
    <TextBox Text="{Binding Name}"></TextBox>
    <Button Command="{s:Action SayHello}">click</Button>
</StackPanel>
```
UserControl1ViewModel.cs
```c#
public string Name { get; set; } = "UserControl1";
public void SayHello()
{
    Name = "Hello " + Name;
}
```
I want call SayHello() in UserControl1ViewModel ,but it find the method in MainViewModel, and tell me "Unable to find method SayHello on target MainViewModel”.
How can I let s:Action change the target to UserControl1ViewModel?
Thanks.

**Comment by RyanYANG52** [comment]
```<ContentControl Grid.Row="1" Content="{Binding CurrentViewModel}" />``` change to ```<ContentControl Grid.Row="1" s:View.Model="{Binding CurrentViewModel}" />```

**Comment by canton7** [comment]
Action's don't use the DataContext at all - they look a the ActionTarget ([see the docs](https://github.com/canton7/Stylet/wiki/Actions#the-viewactiontarget)).

When you let Stylet bind a View and its ViewModel together, the View's ActionTarget is set to the ViewModel. However when you do it yourself, as you're doing here, that doesn't happen. Therefore the `UserControl1View` / `UserControl2View` inherits the ActionTarget of its parent, which is `MainViewModel`, which is why it tries to invoke the action on the `MainViewModel`.

The trivial fix is to set the ActionTarget on the ContentControl:

```xml
<ContentControl Grid.Row="1" Content="{Binding CurrentViewModel}" s:View.ActionTarget="{Binding CurrentViewModel}" />
```

However as @RyanYANG52 noted, this isn't the normal way of doing this sort of thing with Stylet. [As noted in the docs](https://github.com/canton7/Stylet/wiki/ViewModel-First), the normal way to do this is to let Stylet create the View for the ViewModel, using `s:View.Model`. Your entire xaml file can be replaced with:

```xml
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal">
            <Button Command="{s:Action SwitchVM}" CommandParameter="uc1">UserControl1</Button>
            <Button Command="{s:Action SwitchVM}" CommandParameter="uc2">UserControl2</Button>
        </StackPanel>
        <ContentControl Grid.Row="1" s:View.Model="{Binding CurrentViewModel}" />
</Grid>
```

(Note the lack of `DataTemplates`).

**Comment by Xheng1213** [comment]
Thank you! I got it!
