### ISSUE TITLE
View.ActionTarget not set on control System.Windows.Controls.Button:

### ISSUE THREAD

**Issue by Snuger** [canton7/Stylet#76]
I made an example, the main page main (mainViewmodel), sub-page A page (AviewModel), use the Frame to display the sub-page in the main page, use s:action in the sub-page, prompt View.ActionTarget not set on control System. Windows.Controls.Button: Test (method GetSelectItem).
So, add s:View.ActionTarget,

` <DockPanel>
        <DockPanel.DataContext>
            <vmodel:ListBoxSampleViewModel/>
        </DockPanel.DataContext>
 <Button DockPanel.Dock="Top" Content="测试" s:View.ActionTarget="{Binding ListBoxSampleViewModel}" Command="{s:Action GetSelectItem,ActionNotFound=Disable}" CommandParameter="{Binding RelativeSource={RelativeSource Mode=Self}}"/>
 </DockPanel>`

DataContext tried a variety of assignments
1: d:DataContext="{d:DesignInstance vmodel:ListBoxSampleViewModel}"
2: this.window.DataContext=new ListBoxSampleViewModel();
3: The upper part of the code

 then the problem still exists, the status returned according to ActionNotFound is available, why?

**Comment by canton7** [comment]
Why not use a `ContentControl` with `s:View.Model` to show the sub-page instead of a frame, [as described in the docs](https://github.com/canton7/Stylet/wiki/ViewModel-First)? That will make sure that the DataContext and ActionTarget are set correctly.

(You probably wanted `s:View.ActionTarget="{Binding}"` in your code above, but that's still the wrong way to do this)

**Comment by Snuger** [comment]
That said, I seem to understand, I am too sloppy.
