### ISSUE TITLE
Idiomatic binding of Views

### ISSUE THREAD

**Issue by Bert-Proesmans** [canton7/Stylet#78]
Hi. Thanks for the hard work on this project!

I have read the wiki, looked at the example projects and went through the issues. My understanding is that this framework is built on top of modern experience with WPF, which is exactly what I'm looking for.
It turns out I have built components of this framework by myself before and am looking for smarter people with smarter projects so maintenance effort is at least shared.

I'm looking for more information about the decision to keep each WPF FrameworkElement within their own XAML file in comparison with defining DataTemplates within resource dictionaries. 

I personally used the latter and trusted on the Binding engine to show the correct view for each VM I bound to ContentControl.
This certainly has downsides; 
1. organization of resources is hard;
2. you must register each dictionary file in a MergedDictionary;
3. Each ViewModel MUST be a type instance without generic arguments.

There are also upsides; resources are loaded per bundle, XAML type safety and refactoring.
Until now I thought this was the idiomatic way to approach UI construction with the intention of making the VM UI-agnostic. Also all interaction UI->VM should be pure, for example, the Detail command should directly take the SelectedItem from ListElement as a parameter, not through a binding on the ListElement.SelectedItem.

I looked at ViewManager code and it achieves 2 things, as i currently understand;

1. Allow VM to access the UI through IViewAware;
2. Set the ActionTarget to the closest outer ViewModel (but overridable).

Having read all documentation I feel like 1. is implicitly supported. There is no explicit consensus about accessing the UI, so the option is provided regardless.
2. is required to (attempt at) find the correct VM from a (possibly) detached tree,

So given this context, following are my questions;
* Are these assumptions true?
* Should a developer be able to access the UI, using the VM as DataContext? 
Would it be idiomatic to use XAML DataTemplates otherwise?
* Are there more reasons that support this behaviour?
* Any additional up-/downsides I should know?

Optionally; would having a custom ViewManager that loads resources from DLL resource stream ([like described here](https://stackoverflow.com/a/5185454)) give me headaches in the long run? What do I actually gain/lose in performance?

Sorry for blowing this summary out of proportion. I feel like these answers can only come from experience with WPF fundamentals (which I severely lack). I'd love for anyone to chip in and discuss. 
Maybe this should move elsewhere, just let me know.

Thank you for reading,
Bert

**Comment by canton7** [comment]
There's a lot to get through there!

Stylet follows the model of one View FrameworkElement per VM class because that's what Caliburn.Micro did, essentially. I've always though that the DataTemplate approach to MVVM was a hack born out of necessity - without any MVVM framework to choose the correct View for a ViewModel it at least gives you a route to doing this, but it comes with plenty of downsides. In addition to the ones you noted:

1. Each view can only be used with a single ViewModel
2. There's no way for an MVVM framework to get involved in the View construction process.

Point 2 is important. With the approach that Caliburn.Micro and Stylet take, the MVVM framework is responsible for instantiating the view, and binding it to the VM. That means it can insert its own logic at that point: Caliburn.Micro used that to do its convention-based bindings; Stylet uses it to set the ActionTarget.

You can still get a level of XAML type safety by setting `d:DataContext` in your view.

-----------------------------

Allowing the VM to directly the View is allowed but not recommended. Sometimes however the only way to solve a particularly gnarly problem is to do this, so the backdoor's available to people who need it.

The ActionTarget stuff is a little more complex than you describe. The general idea is that the ActionTarget is always set to the enclosing ViewModel. Take for example a ListView driven from the VM (through e.g. a `BindableCollection<RowViewModel>` property), where each row in the ListView is driven from a `RowViewModel` instance. There's a DataTemplate for each row defined in the ListView (so there's no View for `RowViewModel`), and that puts a button on each row. When you click the button, you want that click event to be handled by the main ViewModel, and not by `RowViewModel`. Getting back the parent DataContext is a classic WPF annoyance. This is what the ActionTarget solves - because it is inherited by each row, and it's set to the `RowViewModel` instance for each row, it can be used to get back the parent ViewModel.

There's some extra logic for if there's a detached tree, but that's an edge case.

---------------------

> Should a developer be able to access the UI, using the VM as DataContext?
Would it be idiomatic to use XAML DataTemplates otherwise?

I'm not entirely sure I follow the question. Where are they trying to access the UI from? Can you give an example?

> Are there more reasons that support this behaviour?

Which behaviour? ActionTargets, or letting the framework instantiate the View for each VM? Or something else?

> Optionally; would having a custom ViewManager that loads resources from DLL resource stream (like described here) give me headaches in the long run? 

What sort of resources are you loading? What are you doing with them?

**Comment by Bert-Proesmans** [comment]
Thank you for taking the time to thoroughly answer my questions. The explanations are clear so no further questions about that.

> Should a developer be able to access the UI, using the VM as DataContext?
Would it be idiomatic to use XAML DataTemplates otherwise?

That question was answered earlier. View access using its ViewModel as a proxy is not recommended, but the backdoor is there for obscure cases.
If needing the ability to bind multiple Views to a single VM is a dealbreaker, DataTemplates are not the way to go.

Thinking about the possible obscure reasons for accessing the View;
How would one approach UI extensibility where the third party will provide glue code, ViewModels code and FrameworkElement definitions in XAML?
I'm not immediately seeing how this would/could be implemented cleanly.

> What sort of resources are you loading? What are you doing with them?

The idea was to organize and load resource dictionaries, containing VM DataTemplates, in some clever way to keep loading times to a minimum. The actual problem here is me who doesn't properly understand how actual compilation/embedding of FrameworkElement definitions and ResourceDictionary definition files happens.
Anyway, this point can be forgotten because the complexity would not outweigh the ease of use of one FrameworkElement per XAML file.

**Comment by canton7** [comment]
> How would one approach UI extensibility where the third party will provide glue code, ViewModels code and FrameworkElement definitions in XAML?

I'm not entirely sure what you're suggesting. What sort of glue code are you referring to? If the third-party is providing code which uses Stylet, then no problem. If the third-party is providing code which uses some other MVVM framework, or uses no MVVM framework at all, then those parts of your application will probably have to be constructed to use whatever ecosystem the third-party code is using.

Most third-party controls I've seen are simply the UI control -- no VM, etc. In a few cases I've seen the third-party code consist of UI controls and then a separate model which your VM needs to own, but that's not dependent on any sort of MVVM framework, and you can integrate it into whatever.

> The idea was to organize and load resource dictionaries, containing VM DataTemplates, in some clever way to keep loading times to a minimum. 

I've never seen this done. I've never come across instantiating FrameworkElements as being a bottleneck. Remember that they're loaded when they're instantiated, which in Stylet is when lazily. In the few cases where loading XAML has been an issue (mainly Xamarin.Forms), the solution is to rewrite specific UI controls in C# rather than XAML, but again I've never seen that done in WPF.

> The actual problem here is me who doesn't properly understand how actual compilation/embedding of FrameworkElement definitions and ResourceDictionary definition files happens.

XAML is compiled to BAML, and is stored in your assembly as resources. When a control is instantiated, its InitializeComponent method loads that BAML.

**Comment by canton7** [comment]
Reading your post again, it looks like you previously experienced performance issues when you wrote all of your VMs as DataTemplates and put them into one huge ResourceDictionary (since they were all loaded together at startup), hence the fancy loading DateTemplates from resources yourself?

That should not be a problem if you just use things the way that the WPF authors intended: FrameworkElements for UI elements, DataTemplates for small things inside a FrameworkElement (and owned by the enclosing FrameworkElement). FrameworkElements will be loaded lazily, and will be released when they're no longer needed.

**Comment by Bert-Proesmans** [comment]
Ok, that's clear. Thank you for your knowledge!
