### ISSUE TITLE
How to test `RequestClose` method in unit test?

### ISSUE THREAD

**Issue by wakuflair** [canton7/Stylet#81]
Hi, I'm testing a ViewModel, which will call `RequestClose(true)` somewhere, the unit test method is like this:

``` csharp
        public void LoginTest()
        {
            var vm = _container.Get<LoginViewModel>();
            vm.UserName = "waku";
            vm.Password = "123";
            vm.Login();

           // Here how can I assert that the ReuqestClose is called and the result value is true?
        }
``` 

Now it failed with the exception:
```
Unable to close ViewModel XXX.LoginViewModel as it must have a conductor as a parent (note that windows and dialogs automatically have such a parent)
```

I know it's related to `WindowConductor`, but just can't figure it out.

**Comment by canton7** [comment]
You can see that exception [raised here](https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/Screen.cs#L314). From there, we can tell that this is because either `this.Parent` isn't set of its value isn't an `IChildDelegate`.

The `Parent` property is [publically settable](https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/Screen.cs#L263) (and it's set by a conductor, if there is one).

For your test, create a mock which implements [`IChildDelegate`](https://github.com/canton7/Stylet/blob/4fa7b9ca1a45e8d7455b101d7fed5cdc2990d069/Stylet/IConductor.cs#L34), set `LoginViewModel.Parent = yourModel;`, then test that your mock's `CloseItem` method is called.

**Comment by wakuflair** [comment]
It works! Thanks @canton7 !
